sudo: true
services:
    - docker

before_install:
    - docker info
    - docker version

script:
    - docker run -i -w /usr/local/share -v $(pwd):/usr/local/share -e PLAYBOOK=tests/jmeter.yml williamyeh/ansible:ubuntu16.04-onbuild ansible-playbook-wrapper    > result-ubuntu16.04
    - docker run -i -w /usr/local/share -v $(pwd):/usr/local/share -e PLAYBOOK=tests/jmeter.yml williamyeh/ansible:debian9-onbuild     ansible-playbook-wrapper    > result-debian9
    - docker run -i -w /usr/local/share -v $(pwd):/usr/local/share -e PLAYBOOK=tests/jmeter.yml williamyeh/ansible:centos7-onbuild     ansible-playbook-wrapper    > result-centos7
    - docker run -i -w /usr/local/share -v $(pwd):/usr/local/share -e PLAYBOOK=tests/jmeter.yml williamyeh/ansible:alpine3-onbuild     ansible-playbook-wrapper    > result-alpine3

    - echo "==> Validating the test results..."
    - sh -c "[ -s result-ubuntu16.04 ]"
    - sh -c "[ -s result-debian8     ]"
    - sh -c "[ -s result-centos7     ]"
    - sh -c "[ -s result-alpine3     ]"

notifications:
    webhooks: https://galaxy.ansible.com/api/v1/notifications/
