sudo: true
services:
    - docker

before_install:
    - docker info
    - docker version

script:
    - docker run -i williamyeh/ansible:master-ubuntu16.04-onbuild   > result-ubuntu16.04
    - docker run -i williamyeh/ansible:master-ubuntu14.04-onbuild   > result-ubuntu14.04
    - docker run -i williamyeh/ansible:master-ubuntu12.04-onbuild   > result-ubuntu12.04
    - docker run -i williamyeh/ansible:master-debian9-onbuild       > result-debian9
    - docker run -i williamyeh/ansible:master-debian8-onbuild       > result-debian8
    - docker run -i williamyeh/ansible:master-centos7-onbuild       > result-centos7
    #- docker run -i williamyeh/ansible:master-centos6-onbuild       > result-centos6
    - docker run -i williamyeh/ansible:master-alpine3-onbuild       > result-alpine3

    - echo "==> Validating the test results..."
    - sh -c "[ -s result-ubuntu16.04 ]"
    - sh -c "[ -s result-ubuntu14.04 ]"
    - sh -c "[ -s result-ubuntu12.04 ]"
    - sh -c "[ -s result-debian8     ]"
    - sh -c "[ -s result-debian7     ]"
    - sh -c "[ -s result-centos7     ]"
    #- sh -c "[ -s result-centos6     ]"
    - sh -c "[ -s result-alpine3     ]"

notifications:
    webhooks: https://galaxy.ansible.com/api/v1/notifications/
    

