sudo: true
services:
    - docker

before_install:
    - docker info
    - docker version

script:
    - docker run -i -w /root -v $(pwd):/root williamyeh/ansible:master-ubuntu12.04-onbuild ansible-playbook-wrapper -c local tests/jmeter.yml   > result-ubuntu16.04
    - docker run -i -w /root -v $(pwd):/root williamyeh/ansible:master-ubuntu14.04-onbuild ansible-playbook-wrapper -c local tests/jmeter.yml   > result-ubuntu14.04
    - docker run -i -w /root -v $(pwd):/root williamyeh/ansible:master-ubuntu12.04-onbuild ansible-playbook-wrapper -c local tests/jmeter.yml   > result-ubuntu12.04
    - docker run -i -w /root -v $(pwd):/root williamyeh/ansible:master-debian9-onbuild     ansible-playbook-wrapper -c local tests/jmeter.yml   > result-debian9
    - docker run -i -w /root -v $(pwd):/root williamyeh/ansible:master-debian8-onbuild     ansible-playbook-wrapper -c local tests/jmeter.yml   > result-debian8
    - docker run -i -w /root -v $(pwd):/root williamyeh/ansible:master-centos7-onbuild     ansible-playbook-wrapper -c local tests/jmeter.yml   > result-centos7
    - docker run -i -w /root -v $(pwd):/root williamyeh/ansible:master-centos6-onbuild     ansible-playbook-wrapper -c local tests/jmeter.yml   > result-centos6
    - docker run -i -w /root -v $(pwd):/root williamyeh/ansible:master-alpine3-onbuild     ansible-playbook-wrapper -c local tests/jmeter.yml   > result-alpine3

    - echo "==> Validating the test results..."
    - sh -c "[ -s result-ubuntu16.04 ]"
    - sh -c "[ -s result-ubuntu14.04 ]"
    - sh -c "[ -s result-ubuntu12.04 ]"
    - sh -c "[ -s result-debian8     ]"
    - sh -c "[ -s result-debian7     ]"
    - sh -c "[ -s result-centos7     ]"
    - sh -c "[ -s result-centos6     ]"
    - sh -c "[ -s result-alpine3     ]"

notifications:
    webhooks: https://galaxy.ansible.com/api/v1/notifications/
